apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-injector
  namespace: test
  labels:
    app: sidecar-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-injector
  template:
    metadata:
      labels:
        app: sidecar-injector
    spec:
      containers:
        - name: sidecar-injector
          image: harbor.hzxingzai.cn/tools/injector:latest
          imagePullPolicy: Always
          args:
            - -certDir=/etc/webhook/certs
            - -port=8443
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: sidecar-injector-certs