apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: test
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: test
spec:
  secretName: sidecar-injector-certs
  dnsNames:
    - sidecar-injector-service.test.svc
    - sidecar-injector-service.test.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer